### ISSUE TITLE
Fix path prefix and add under review block

### ISSUE THREAD

**Issue by chatchavan** [journalovi/2024-luong-graphical-models#4]
- [x] Fix the path prefix to work with the following URL `https://www.journalovi.org/2024-luong-graphical-models/` (or ideally any URL prefix.

- [x] Add the following HTML block at the top of the page

```
 <p><strong>Under Review:</strong> This paper is <a href="https://www.journalovi.org/under-review.html">under review</a> on the experimental track of the <a href="https://www.journalovi.org/">Journal of Visualization and Interaction</a>. See the <a href="">reviewing process</a>.</p>
```

_Originally posted by @chatchavan in https://github.com/journalovi/2024-luong-graphical-models/issues/1#issuecomment-2076928315_

**Comment by chatchavan** [comment]
@mjskay The authors fixed the issues above. Could you set the correct permission level for `@vuluongj20`?

**Comment by mjskay** [comment]
Thanks!

@vuluongj20 has write access and I have put a branch protection rule in to prevent re-writing history on `main`, so I think we're good.
